#!/usr/bin/env bash

# shellcheck disable=SC1090

# Set strict bash mode
set -euo pipefail

# Default varable values
TOOLBOX_LOG_LEVEL=${TOOLBOX_LOG_LEVEL:-INFO}

# Trace with "-x" mode
if [ "${TOOLBOX_LOG_LEVEL}" == "TRACE" ]; then
  set -x
fi

# Includes
# https://stackoverflow.com/a/12694189
SCRIPT_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$SCRIPT_DIR" ]]; then SCRIPT_DIR="$PWD"; fi
. "$SCRIPT_DIR/includes/util.sh"
. "$SCRIPT_DIR/includes/docker.sh"

_exec_tool "${@}"
